---
name: dryrun CMake
on:
- pull_request
- workflow_dispatch

jobs:
  dryrun:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.22.x'

    - name: CMake Version
      run: cmake --version

    - run: mkdir -p tmp

    - name: dryrun CMake
      working-directory: tmp
      run: cmake ../ && cmake --build . -- -n
