name: clang-tidy-review # https://github.com/marketplace/actions/clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Optionally generate compile_commands.json
    - uses: ZedThree/clang-tidy-review@v0.7.0
      id: review
      with:
        clang_tidy_version: 11
        ## List of packages to install
        #apt_packages: liblapack-dev
        # CMake command to run in order to generate compile_commands.json
        cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
